# Tell Spring Boot to explicitly load application-local.properties
spring.profiles.active=local
spring.config.import=optional:file:./src/main/resources/application-local.properties

# Application Info
spring.application.name=ecommerce

# Hibernate & JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true